const fs = require('fs'), os = require('os'), path = require('path'), http = require('http'), { spawn } = require('child_process'), io = require('socket.io-client');
const root = path.join(__dirname, '..'), rd = (f) => fs.readFileSync(path.join(root, f), 'utf8'), serverJs = rd('server.js'), indexHtml = rd('index.html'), viewerHtml = rd('viewer.html');
let fail = 0;
const ok = (name, cond) => { console.log((cond ? 'ok' : 'FAIL') + ' ' + name); cond || fail++; };
ok('viewer falls back to the socket stream without WebRTC', /sockMode = typeof RTCPeerConnection === 'undefined' \|\| urlParams\.get\('transport'\) === 'socket'/.test(viewerHtml) && /socket\.emit\('sv', \{ t: 'want', roomId \}\)/.test(viewerHtml));
ok('viewer acks every frame it receives', /socket\.emit\('sv', \{ t: 'ack', roomId, seq: d\.seq \}\);\n  const c = /.test(viewerHtml));
ok('viewer configures the decoder with the avcC description', /description: d\.desc/.test(viewerHtml));
ok('host encodes avc with a description for WebKit', /avc: \{ format: 'avc' \}/.test(indexHtml) && /decoderConfig\.description/.test(indexHtml));
ok('host drops frames before encoding when a viewer falls behind', /st\.seq - st\.ack > 3/.test(indexHtml));
ok('host stops the socket stream when the viewer leaves', /if \(id\) svStop\(id\);/.test(indexHtml));
ok('server raises the socket.io message cap for keyframes', /maxHttpBufferSize: 4e6/.test(serverJs));
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'amni-sv-'));
fs.mkdirSync(path.join(tmp, 'amni-connect'), { recursive: true });
fs.writeFileSync(path.join(tmp, 'amni-connect', 'room.json'), JSON.stringify({ id: 'SV-TEST' }));
const PORT = 33996, child = spawn(process.execPath, [path.join(root, 'server.js')], { env: { ...process.env, PORT: String(PORT), APPDATA: tmp, ALLOWED_ORIGINS: '*' }, stdio: 'ignore' });
const wait = (ms) => new Promise(r => setTimeout(r, ms)), sock = () => io(`http://127.0.0.1:${PORT}`, { transports: ['websocket'] }), connect = (s) => new Promise(r => s.on('connect', () => r(s.id)));
const health = () => new Promise((res, rej) => http.get({ host: '127.0.0.1', port: PORT, path: '/health' }, (r) => { r.resume(); res(r.statusCode); }).on('error', rej));
const got = (s, n = 400) => new Promise(r => { const a = []; s.on('sv', d => a.push(d)); setTimeout(() => r(a), n); });
(async () => {
  let up = false;
  for (let i = 0; i < 40 && !up; i++) { await wait(200); try { up = (await health()) === 200; } catch (_) {} }
  ok('test server up', up);
  const host = sock(), v1 = sock(), v2 = sock(), out = sock();
  await Promise.all([host, v1, v2, out].map(connect));
  host.emit('create-room', 'SV-TEST'); await wait(150);
  v1.emit('join-room', 'SV-TEST'); v2.emit('join-room', 'SV-TEST'); await wait(200);
  const hostSaw = got(host);
  v1.emit('sv', { t: 'want', roomId: 'SV-TEST' }); v1.emit('sv', { t: 'frame', roomId: 'SV-TEST', to: v2.id, data: Buffer.from('x') }); out.emit('sv', { t: 'want', roomId: 'SV-TEST' });
  const h = await hostSaw;
  ok('viewer want reaches the host with from', h.some(d => d.t === 'want' && d.from === v1.id));
  ok('a viewer cannot push frames', !h.some(d => d.t === 'frame'));
  ok('a socket that never joined is ignored', !h.some(d => d.from === out.id));
  const [a1, a2, a3] = [got(v1), got(v2), got(out)];
  host.emit('sv', { t: 'frame', roomId: 'SV-TEST', to: v1.id, seq: 1, key: true, codec: 'avc1.42E028', data: Buffer.alloc(1500000, 7) });
  host.emit('sv', { t: 'frame', roomId: 'SV-TEST', to: out.id, seq: 2, data: Buffer.from('y') });
  const [r1, r2, r3] = await Promise.all([a1, a2, a3]);
  ok('host frame reaches only the addressed viewer, 1.5 MB keyframe intact', r1.length === 1 && r1[0].seq === 1 && r1[0].data.byteLength === 1500000);
  ok('other viewers do not get it', r2.length === 0);
  ok('host cannot address a socket outside the room', r3.length === 0);
  [host, v1, v2, out].forEach(s => s.close()); child.kill(); fs.rmSync(tmp, { recursive: true, force: true });
  console.log(fail ? `${fail} failed` : 'all ok'); process.exit(fail ? 1 : 0);
})();
