const fs = require('fs');
const os = require('os');
const path = require('path');
const http = require('http');
const { spawn } = require('child_process');
const io = require('socket.io-client');
const root = path.join(__dirname, '..');
const serverJs = fs.readFileSync(path.join(root, 'server.js'), 'utf8');
const indexHtml = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const viewerHtml = fs.readFileSync(path.join(root, 'viewer.html'), 'utf8');
let fail = 0;
const ok = (name, cond) => { console.log((cond ? 'ok' : 'FAIL') + ' ' + name); cond || fail++; };
ok('host keeps one RTCPeerConnection per viewer', /const peers = new Map\(\)/.test(indexHtml) && /function createPeer\(id\)/.test(indexHtml) && /peers\.set\(id, peer\)/.test(indexHtml));
ok('host offers are addressed to a viewer', /socket\.emit\('offer', \{ roomId, offer, to: viewerId \}\)/.test(indexHtml));
ok('host ICE is addressed to a viewer', /emitIce\(candidate, id\)/.test(indexHtml) && /candidate: init, to \}/.test(indexHtml));
ok('host picks the peer by the answer sender', /pcFor\(from\)/.test(indexHtml) && /setRemoteMunged\(answer, target\)/.test(indexHtml));
ok('a second join no longer closes the first peer', !/if \(live && info\.id === lastViewerId\)/.test(indexHtml) && /peer && isLive\(peer\.pc\)/.test(indexHtml));
ok('viewer-left drops only that viewer', /if \(id\) dropViewerPc\(id\)/.test(indexHtml));
ok('screen frames fan out to every HW viewer', /const screenOuts = \(\)/.test(indexHtml) && /outs\.forEach\(ch =>/.test(indexHtml));
ok('clipboard sync fans out to every viewer', /peerList\(\)\.map\(p => p\.clip\)/.test(indexHtml));
ok('move seq is tracked per viewer', /function staleMove\(seq, peer\)/.test(indexHtml) && /peer\.moveSeq/.test(indexHtml));
ok('viewer ignores offers addressed to someone else', /if \(to && socket\.id && to !== socket\.id\) return;/.test(viewerHtml));
ok('server routes by to/from', /\['offer', 'answer', 'ice-candidate'\]\.forEach\(route\)/.test(serverJs) && /from: socket\.id/.test(serverJs));

const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'amni-multi-'));
fs.mkdirSync(path.join(tmp, 'amni-connect'), { recursive: true });
fs.writeFileSync(path.join(tmp, 'amni-connect', 'room.json'), JSON.stringify({ id: 'MULTI-PC' }));
const PORT = 33995;
const child = spawn(process.execPath, [path.join(root, 'server.js')], { env: { ...process.env, PORT: String(PORT), APPDATA: tmp, ALLOWED_ORIGINS: '*' }, stdio: ['ignore', 'pipe', 'pipe'] });
const req = (p) => new Promise((resolve, reject) => { const r = http.request({ host: '127.0.0.1', port: PORT, path: p, method: 'GET' }, (res) => { res.resume(); res.on('end', () => resolve(res.statusCode)); }); r.on('error', reject); r.end(); });
const wait = (ms) => new Promise(r => setTimeout(r, ms));
const sock = () => io(`http://127.0.0.1:${PORT}`, { transports: ['websocket'] });
const connect = (s) => new Promise((resolve) => s.on('connect', () => resolve(s.id)));
(async () => {
  let up = false;
  for (let i = 0; i < 40 && !up; i++) { await wait(200); try { up = (await req('/health')) === 200; } catch (_) {} }
  ok('test server up', up);
  const host = sock(), v1 = sock(), v2 = sock();
  await Promise.all([connect(host), connect(v1), connect(v2)]);
  const joined = [];
  host.on('viewer-joined', (p) => joined.push(p && p.id));
  await new Promise((resolve) => { host.on('room-created', resolve); host.emit('create-room', 'MULTI-PC'); });
  const join = (s) => new Promise((resolve) => { s.on('room-joined', resolve); s.emit('join-room', 'MULTI-PC'); });
  await join(v1); await join(v2);
  await wait(200);
  ok('host sees both viewers join', joined.includes(v1.id) && joined.includes(v2.id));
  const got = { v1: [], v2: [], host: [] };
  v1.on('offer', (d) => got.v1.push(d)); v2.on('offer', (d) => got.v2.push(d));
  v1.on('ice-candidate', (d) => got.v1.push(d)); v2.on('ice-candidate', (d) => got.v2.push(d));
  host.on('answer', (d) => got.host.push(d)); host.on('ice-candidate', (d) => got.host.push(d));
  v1.on('answer', (d) => got.v1.push(d)); v2.on('answer', (d) => got.v2.push(d));
  host.emit('offer', { roomId: 'MULTI-PC', offer: { type: 'offer', sdp: 'A' }, to: v1.id });
  host.emit('ice-candidate', { roomId: 'MULTI-PC', candidate: { candidate: 'c1' }, to: v2.id });
  await wait(300);
  ok('addressed offer reaches only that viewer', got.v1.length === 1 && got.v1[0].offer.sdp === 'A' && got.v1[0].from === host.id && !got.v2.some(d => d.offer));
  ok('addressed ICE reaches only that viewer', got.v2.length === 1 && got.v2[0].candidate.candidate === 'c1' && got.v2[0].from === host.id && !got.v1.some(d => d.candidate));
  v1.emit('answer', { roomId: 'MULTI-PC', answer: { type: 'answer', sdp: 'B' } });
  v2.emit('ice-candidate', { roomId: 'MULTI-PC', candidate: { candidate: 'c2' } });
  await wait(300);
  ok('viewer answer goes to the host stamped with from', got.host.some(d => d.answer && d.answer.sdp === 'B' && d.from === v1.id));
  ok('viewer ICE goes to the host stamped with from', got.host.some(d => d.candidate && d.candidate.candidate === 'c2' && d.from === v2.id));
  ok('viewers never see each other\'s signaling', !got.v1.some(d => d.answer || (d.candidate && d.candidate.candidate === 'c2')) && !got.v2.some(d => d.answer));
  got.v1.length = 0; got.v2.length = 0;
  host.emit('offer', { roomId: 'MULTI-PC', offer: { type: 'offer', sdp: 'C' } });
  await wait(300);
  ok('an unaddressed host offer still broadcasts (old viewer compat)', got.v1.length === 1 && got.v2.length === 1);
  const left = [];
  host.on('viewer-left', (p) => left.push(p && p.id));
  const v1Id = v1.id;
  v1.close();
  for (let i = 0; i < 20 && !left.length; i++) await wait(100);
  ok('one viewer leaving reports only that id', left.length === 1 && left[0] === v1Id);
  v2.close(); host.close();
  child.kill();
  fs.rmSync(tmp, { recursive: true, force: true });
  console.log(fail ? `${fail} FAILED` : 'all ok');
  process.exit(fail ? 1 : 0);
})();
