const fs = require('fs');
const os = require('os');
const path = require('path');
const http = require('http');
const { spawn } = require('child_process');
const io = require('socket.io-client');
const root = path.join(__dirname, '..');
const serverPath = process.argv[2] || path.join(root, 'server.js');
const viewerPath = process.argv[3] || path.join(root, 'viewer.html');
const indexPath = process.argv[4] || path.join(root, 'index.html');
const mainPath = process.argv[5] || path.join(root, 'main.js');
const read = (p) => fs.readFileSync(p, 'utf8');
const viewer = read(viewerPath), index = read(indexPath), mainJs = read(mainPath), serverJs = read(serverPath);
let fail = 0;
const ok = (name, cond) => { console.log((cond ? 'ok' : 'FAIL') + ' ' + name); cond || fail++; };
ok('server mounts auth routes and gates join-room', /auth\.routes\(app\)/.test(serverJs) && /auth\.allowed\(socket\.handshake\.headers\)/.test(serverJs));
ok('server refuses remote hosting', /auth\.isRemote\(socket\.handshake\.headers\)/.test(serverJs));
ok('viewer has enroll + unlock flows', /navigator\.credentials\.create/.test(viewer) && /navigator\.credentials\.get/.test(viewer) && /showUnlock\(origin, joinNow\)/.test(viewer));
ok('viewer only prompts for a passkey when status.required', /authState\.required/.test(viewer));
ok('passkey gate has a single off switch', /REQUIRE_PASSKEY = false/.test(read(path.join(root, 'auth.js'))));
ok('passkey UI replaces the whole connect screen', /function fillConnectCard/.test(viewer) && /screen\.innerHTML/.test(viewer) && !/enroll-card/.test(viewer) && !/unlock-card/.test(viewer));
ok('viewer maps the Windows Hello UV error', /function passkeyErr/.test(viewer) && /user verification/.test(viewer));
ok('host window has enroll QR + device list', /enrollDevice\(\)/.test(index) && /\/auth\/enroll-token/.test(index) && /\/auth\/devices/.test(index));
ok('main spawns cloudflared with the tunnel token', /'tunnel', '--no-autoupdate', 'run', '--token'/.test(mainJs) && /stopTunnel\(\)/.test(mainJs));
const HOST = 'connect.test.example';
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'amni-auth-'));
fs.mkdirSync(path.join(tmp, 'amni-connect'), { recursive: true });
fs.writeFileSync(path.join(tmp, 'amni-connect', 'tunnel.json'), JSON.stringify({ hostname: HOST, token: 'x' }));
const PORT = 33993;
const child = spawn(process.execPath, [serverPath], { env: { ...process.env, PORT: String(PORT), APPDATA: tmp, ALLOWED_ORIGINS: '*' }, stdio: ['ignore', 'pipe', 'pipe'] });
const req = (method, p, body, headers = {}) => new Promise((resolve, reject) => {
  const data = body ? JSON.stringify(body) : null;
  const r = http.request({ host: '127.0.0.1', port: PORT, path: p, method, headers: { ...(data ? { 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(data) } : {}), ...headers } }, (res) => { let b = ''; res.on('data', d => b += d); res.on('end', () => { let j = null; try { j = JSON.parse(b); } catch (_) {} resolve({ status: res.statusCode, json: j, body: b, headers: res.headers }); }); });
  r.on('error', reject); data && r.write(data); r.end();
});
const wait = (ms) => new Promise(r => setTimeout(r, ms));
const join = (extraHeaders, code) => new Promise((resolve) => {
  const s = io(`http://127.0.0.1:${PORT}`, { transports: ['websocket'], extraHeaders });
  const t = setTimeout(() => { s.close(); resolve('timeout'); }, 3000);
  s.on('connect', () => s.emit('join-room', code));
  s.on('room-joined', () => { clearTimeout(t); s.close(); resolve('joined'); });
  s.on('auth-required', () => { clearTimeout(t); s.close(); resolve('auth-required'); });
  s.on('error', (e) => { if (/Room not found/.test(String(e))) { clearTimeout(t); s.close(); resolve('room-not-found'); } });
});
(async () => {
  let up = false;
  for (let i = 0; i < 40 && !up; i++) { await wait(200); try { up = (await req('GET', '/health')).status === 200; } catch (_) {} }
  ok('test server up', up);
  const host = io(`http://127.0.0.1:${PORT}`, { transports: ['websocket'] });
  await new Promise(r => { host.on('connect', () => host.emit('create-room', 'TESTROOM')); host.on('room-created', r); });
  const st = (await req('GET', '/auth/status')).json;
  ok('status: enabled with hostname, local request not remote', st && st.enabled && st.hostname === HOST && st.remote === false);
  const rst = (await req('GET', '/auth/status', null, { Host: HOST })).json;
  ok('status: Host header of the tunnel = remote', rst && rst.remote === true && rst.authed === false && rst.required === false);
  ok('LAN/loopback join without passkey still works', (await join({}, 'TESTROOM')) === 'joined');
  ok('tunnel join with only the room code works', (await join({ Host: HOST }, 'TESTROOM')) === 'joined');
  const remoteHost = io(`http://127.0.0.1:${PORT}`, { transports: ['websocket'], extraHeaders: { Host: HOST } });
  const hostErr = await new Promise(r => { const t = setTimeout(() => r('timeout'), 2000); remoteHost.on('connect', () => remoteHost.emit('create-room', 'EVILROOM')); remoteHost.on('room-created', () => { clearTimeout(t); r('created'); }); remoteHost.on('error', (e) => { clearTimeout(t); r(String(e)); }); });
  remoteHost.close();
  ok('remote socket cannot host a room', /host window/.test(hostErr));
  ok('/ice-servers via tunnel is open while passkeys are off', (await req('GET', '/ice-servers', null, { Host: HOST })).status === 200);
  ok('/ice-servers on LAN is open', (await req('GET', '/ice-servers')).status === 200);
  ok('enroll-token refused from the tunnel', (await req('POST', '/auth/enroll-token', {}, { Host: HOST })).status === 403);
  const tok = (await req('POST', '/auth/enroll-token', { code: 'TESTROOM' })).json;
  const pkgVer = JSON.parse(read(path.join(root, 'package.json'))).version;
  ok('enroll-token issued from the host window', tok && tok.token && tok.url === `https://${HOST}/viewer?enroll=${tok.token}&code=TESTROOM&v=${pkgVer}`);
  ok('bad enroll token refused', (await req('POST', '/auth/enroll/options', { token: 'nope', name: 'x' })).status === 403);
  const opts = (await req('POST', '/auth/enroll/options', { token: tok.token, name: 'Test phone' }, { Host: HOST })).json;
  ok('enroll options carry the rp id and a challenge', opts && opts.rp && opts.rp.id === HOST && typeof opts.challenge === 'string' && opts.challenge.length > 20);
  ok('enroll does not require user verification', opts && opts.authenticatorSelection && opts.authenticatorSelection.userVerification === 'discouraged');
  ok('login refused with no devices', (await req('POST', '/auth/login/options', {}, { Host: HOST })).status === 403);
  const forged = Buffer.from(JSON.stringify({ d: 'x', exp: 9999999999 })).toString('base64url') + '.forged';
  ok('forged session cookie is ignored', (await req('GET', '/auth/me', null, { Host: HOST, Cookie: 'amni_sess=' + forged })).json.authed === false);
  ok('devices list is host-window only', (await req('GET', '/auth/devices', null, { Host: HOST })).status === 403 && (await req('GET', '/auth/devices')).status === 200);
  host.close(); child.kill();
  fs.rmSync(tmp, { recursive: true, force: true });
  console.log(fail ? `${fail} FAILED` : 'all ok');
  process.exit(fail ? 1 : 0);
})();
